export const els = {
  projectList: document.getElementById('projectList'),
  btnNewProject: document.getElementById('btnNewProject'),
  projectTitle: document.getElementById('projectTitle'),
  projectTitleInput: document.getElementById('projectTitleInput'),
  editor: document.getElementById('editor'),
  btnUndo: document.getElementById('btnUndo'),
  btnRedo: document.getElementById('btnRedo'),
  btnPlay: document.getElementById('btnPlay'),
  btnExport: document.getElementById('btnExport'),
  btnExportSettings: document.getElementById('btnExportSettings'),
  processingAlgorithm: document.getElementById('processingAlgorithm'),
  toast: document.getElementById('toast'),
  exportSamplingRate: document.getElementById('exportSamplingRate'),
  exportSettingsModal: document.getElementById('exportSettingsModal'),
  btnExportSettingsDismiss: document.getElementById('btnExportSettingsDismiss'),
  btnExportSettingsClose: document.getElementById('btnExportSettingsClose'),
  btnExportDirSelect: document.getElementById('btnExportDirSelect'),
  btnExportDirClear: document.getElementById('btnExportDirClear'),
  exportDirectoryPath: document.getElementById('exportDirectoryPath'),
  exportDirectoryEnabled: document.getElementById('exportDirectoryEnabled'),
  preventExportOverwrite: document.getElementById('preventExportOverwrite'),
  exportTextFileEnabled: document.getElementById('exportTextFileEnabled'),
  exportTextEncodingGroup: document.getElementById('exportTextEncodingGroup'),
  exportChoiceModal: document.getElementById('exportChoiceModal'),
  btnExportChoiceDismiss: document.getElementById('btnExportChoiceDismiss'),
  btnExportSelected: document.getElementById('btnExportSelected'),
  btnExportAll: document.getElementById('btnExportAll'),
  speedScale: document.getElementById('speedScale'),
  pitchScale: document.getElementById('pitchScale'),
  intonationScale: document.getElementById('intonationScale'),
  volumeScale: document.getElementById('volumeScale'),
  prePhonemeLength: document.getElementById('prePhonemeLength'),
  postPhonemeLength: document.getElementById('postPhonemeLength'),
  speedScaleVal: document.getElementById('speedScaleVal'),
  pitchScaleVal: document.getElementById('pitchScaleVal'),
  intonationScaleVal: document.getElementById('intonationScaleVal'),
  volumeScaleVal: document.getElementById('volumeScaleVal'),
  prePhonemeLengthVal: document.getElementById('prePhonemeLengthVal'),
  postPhonemeLengthVal: document.getElementById('postPhonemeLengthVal'),
  btnDictionary: document.getElementById('btnDictionary'),
  dictionaryModal: document.getElementById('dictionaryModal'),
  dictionaryRows: document.getElementById('dictionaryRows'),
  btnDictDismiss: document.getElementById('btnDictDismiss'),
  btnDictClose: document.getElementById('btnDictClose'),
  btnDictApply: document.getElementById('btnDictApply'),
  btnDictAddRow: document.getElementById('btnDictAddRow'),
  editorWrap: document.getElementById('editorWrap'),
  segmentMirror: document.getElementById('segmentMirror'),
  workspace: document.getElementById('workspace'),
  paramPane: document.getElementById('paramPane'),
  btnSegmentParamReset: document.getElementById('btnSegmentParamReset'),
  btnRegenerateProsody: document.getElementById('btnRegenerateProsody'),
  intonationDock: document.getElementById('intonationDock'),
  intonationPanel: document.getElementById('intonationPanel'),
  intonationContent: document.getElementById('intonationContent'),
  intonationTextStrip: document.getElementById('intonationTextStrip'),
  intonationSliderStrip: document.getElementById('intonationSliderStrip'),
  coeiroinkStatusDot: document.getElementById('coeiroinkStatusDot'),
  coeiroinkStatusText: document.getElementById('coeiroinkStatusText'),
  coeiroinkWarningModal: document.getElementById('coeiroinkWarningModal'),
  coeiroinkWarningTitle: document.getElementById('coeiroinkWarningTitle'),
  coeiroinkWarningMessage: document.getElementById('coeiroinkWarningMessage'),
  coeiroinkWarningFeedback: document.getElementById('coeiroinkWarningFeedback'),
  coeiroinkWarningSpinner: document.getElementById('coeiroinkWarningSpinner'),
  btnCoeiroinkRetry: document.getElementById('btnCoeiroinkRetry'),
  btnCoeiroinkDismiss: document.getElementById('btnCoeiroinkDismiss'),
};

els.btnPlayIconPlay = els.btnPlay.querySelector('.icon-play');
els.btnPlayIconStop = els.btnPlay.querySelector('.icon-stop');
els.waveformCanvas = /** @type {HTMLCanvasElement} */ (document.getElementById('waveformCanvas'));

export const segmentParamControls = {
  speedScale: els.speedScale,
  pitchScale: els.pitchScale,
  intonationScale: els.intonationScale,
  volumeScale: els.volumeScale,
  prePhonemeLength: els.prePhonemeLength,
  postPhonemeLength: els.postPhonemeLength,
  processingAlgorithm: els.processingAlgorithm,
  speedScaleVal: els.speedScaleVal,
  pitchScaleVal: els.pitchScaleVal,
  intonationScaleVal: els.intonationScaleVal,
  volumeScaleVal: els.volumeScaleVal,
  prePhonemeLengthVal: els.prePhonemeLengthVal,
  postPhonemeLengthVal: els.postPhonemeLengthVal,
};
