export const els = {
  projectList: document.getElementById('projectList'),
  btnNewProject: document.getElementById('btnNewProject'),
  projectTitle: document.getElementById('projectTitle'),
  projectTitleInput: document.getElementById('projectTitleInput'),
  editor: document.getElementById('editor'),
  btnUndo: document.getElementById('btnUndo'),
  btnRedo: document.getElementById('btnRedo'),
  btnPlay: document.getElementById('btnPlay'),
  btnExport: document.getElementById('btnExport'),
  processingAlgorithm: document.getElementById('processingAlgorithm'),
  toast: document.getElementById('toast'),
  exportSamplingRate: document.getElementById('exportSamplingRate'),
  speedScale: document.getElementById('speedScale'),
  pitchScale: document.getElementById('pitchScale'),
  intonationScale: document.getElementById('intonationScale'),
  volumeScale: document.getElementById('volumeScale'),
  prePhonemeLength: document.getElementById('prePhonemeLength'),
  postPhonemeLength: document.getElementById('postPhonemeLength'),
  speedScaleVal: document.getElementById('speedScaleVal'),
  pitchScaleVal: document.getElementById('pitchScaleVal'),
  intonationScaleVal: document.getElementById('intonationScaleVal'),
  volumeScaleVal: document.getElementById('volumeScaleVal'),
  prePhonemeLengthVal: document.getElementById('prePhonemeLengthVal'),
  postPhonemeLengthVal: document.getElementById('postPhonemeLengthVal'),
  btnDictionary: document.getElementById('btnDictionary'),
  dictionaryModal: document.getElementById('dictionaryModal'),
  dictionaryRows: document.getElementById('dictionaryRows'),
  btnDictDismiss: document.getElementById('btnDictDismiss'),
  btnDictClose: document.getElementById('btnDictClose'),
  btnDictApply: document.getElementById('btnDictApply'),
  btnDictAddRow: document.getElementById('btnDictAddRow'),
  editorWrap: document.getElementById('editorWrap'),
  segmentMirror: document.getElementById('segmentMirror'),
  workspace: document.getElementById('workspace'),
  paramPane: document.getElementById('paramPane'),
  btnSegmentParamReset: document.getElementById('btnSegmentParamReset'),
  btnSegmentExport: document.getElementById('btnSegmentExport'),
  btnRegenerateProsody: document.getElementById('btnRegenerateProsody'),
  intonationDock: document.getElementById('intonationDock'),
  intonationPanel: document.getElementById('intonationPanel'),
  intonationContent: document.getElementById('intonationContent'),
  intonationTextStrip: document.getElementById('intonationTextStrip'),
  intonationSliderStrip: document.getElementById('intonationSliderStrip'),
};

els.btnPlayIconPlay = els.btnPlay.querySelector('.icon-play');
els.btnPlayIconStop = els.btnPlay.querySelector('.icon-stop');
els.waveformCanvas = /** @type {HTMLCanvasElement} */ (document.getElementById('waveformCanvas'));

export const segmentParamControls = {
  speedScale: els.speedScale,
  pitchScale: els.pitchScale,
  intonationScale: els.intonationScale,
  volumeScale: els.volumeScale,
  prePhonemeLength: els.prePhonemeLength,
  postPhonemeLength: els.postPhonemeLength,
  processingAlgorithm: els.processingAlgorithm,
  speedScaleVal: els.speedScaleVal,
  pitchScaleVal: els.pitchScaleVal,
  intonationScaleVal: els.intonationScaleVal,
  volumeScaleVal: els.volumeScaleVal,
  prePhonemeLengthVal: els.prePhonemeLengthVal,
  postPhonemeLengthVal: els.postPhonemeLengthVal,
};
